### PR TITLE
chore: prevent production logs

### PR DESCRIPTION
**Pull request by 0xLodz**
This PR implements https://github.com/okp4/dataverse-portal/issues/179.

### How to test it locally?
From this branch `chore/prevent-production-logs`,
- add some console.logs whenever you want and test them locally with `npm run dev` (port 5173).
- build your app with `npm run build`, then launch and test it with `npm run preview` (port 4173).

### CODE REVIEW

**Comment by lolottetheclash** [comment]
I wonder if we could do without a new plugin and use the quick config instead 🤔
We could add this: 

```
esbuild: {
    drop: ['console', 'debugger']
  }
```

Knowing that even though Vitejs uses Rollup for the bundle, Esbuild is still used for transpilation and minification in Vite during build. I'm not sure if it's a good idea but maybe we could consider passing this config, what do you think @0xLodz 
 & @fredericvilcot ?

**Comment by 0xLodz** [comment]
> I wonder if we could do without a new plugin and use the quick config instead 🤔 We could add this:
> 
> ```
> esbuild: {
>     drop: ['console', 'debugger']
>   }
> ```
> 
> Knowing that even though Vitejs uses Rollup for the bundle, Esbuild is still used for transpilation and minification in Vite during build. I'm not sure if it's a good idea but maybe we could consider passing this config, what do you think @0xLodz & @fredericvilcot ?

@lolottetheclash thanks, wasn't aware of this built-in config. There are more details [here](https://github.com/vitejs/vite/discussions/7920#discussioncomment-2709119). Sounds better alternative.

**Comment by fredericvilcot** [comment]
> I wonder if we could do without a new plugin and use the quick config instead 🤔 We could add this:
> 
> ```
> esbuild: {
>     drop: ['console', 'debugger']
>   }
> ```
> 
> Knowing that even though Vitejs uses Rollup for the bundle, Esbuild is still used for transpilation and minification in Vite during build. I'm not sure if it's a good idea but maybe we could consider passing this config, what do you think @0xLodz & @fredericvilcot ?

Yes, sounds to be a recommended practice by the Vite's team.
I would suggest however to discriminate by the environment to keep logs on development mode 😌

**Comment by lolottetheclash** [comment]
> > I wonder if we could do without a new plugin and use the quick config instead 🤔 We could add this:
> > ```
> > esbuild: {
> >     drop: ['console', 'debugger']
> >   }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Knowing that even though Vitejs uses Rollup for the bundle, Esbuild is still used for transpilation and minification in Vite during build. I'm not sure if it's a good idea but maybe we could consider passing this config, what do you think @0xLodz & @fredericvilcot ?
> 
> Yes, sounds to be a recommended practice by the Vite's team. I would suggest however to discriminate by the environment to keep logs on development mode 😌

I am not sure to understand... logs are still working on dev mode, am I missing something?

**Comment by fredericvilcot** [comment]
> > > I wonder if we could do without a new plugin and use the quick config instead 🤔 We could add this:
> > > ```
> > > esbuild: {
> > >     drop: ['console', 'debugger']
> > >   }
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > Knowing that even though Vitejs uses Rollup for the bundle, Esbuild is still used for transpilation and minification in Vite during build. I'm not sure if it's a good idea but maybe we could consider passing this config, what do you think @0xLodz & @fredericvilcot ?
> > 
> > 
> > Yes, sounds to be a recommended practice by the Vite's team. I would suggest however to discriminate by the environment to keep logs on development mode 😌
> 
> I am not sure to understand... logs are still working on dev mode, am I missing something?

You may want to keep logs in development mode, to facilitate debugging.
So, as far as I see, we must discriminate env in config like in this example: https://github.com/vitejs/vite/discussions/7920#discussioncomment-4796266

**Comment by lolottetheclash** [comment]
> > > > I wonder if we could do without a new plugin and use the quick config instead 🤔 We could add this:
> > > > ```
> > > > esbuild: {
> > > >     drop: ['console', 'debugger']
> > > >   }
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > Knowing that even though Vitejs uses Rollup for the bundle, Esbuild is still used for transpilation and minification in Vite during build. I'm not sure if it's a good idea but maybe we could consider passing this config, what do you think @0xLodz & @fredericvilcot ?
> > > 
> > > 
> > > Yes, sounds to be a recommended practice by the Vite's team. I would suggest however to discriminate by the environment to keep logs on development mode 😌
> > 
> > 
> > I am not sure to understand... logs are still working on dev mode, am I missing something?
> 
> You may want to keep logs in development mode, to facilitate debugging. So, as far as I see, we must discriminate env in config like in this example: [vitejs/vite#7920 (reply in thread)](https://github.com/vitejs/vite/discussions/7920#discussioncomment-4796266)

Ok I see, but my question is: transpiling and minification are not only happening when building? Is it mandatory to discriminate environments here?

**Comment by fredericvilcot** [comment]
> 

Yes, but when it comes to run the dev server, there is also a build ;)

**Comment by 0xLodz** [comment]
@lolottetheclash @fredericvilcot the config is now updated using the built-in eslint minification drop option.

**Review by fredericvilcot — APPROVED** [review]
Great, thx ☺️

**Pull request merged**
