### PR TITLE
refactor: architectural change for ui

### PR DESCRIPTION
**Pull request by GeoffreyPicard**
Create an ui folder for React application and start new architecture.

Everything related to React application should now be in ui folder.
- Page folder must contain only tree structure (one .tsx and one .scss maximum per folder)
- Views folder contain anything related to what is now called a "view". For example, "dataverse" is a view. It will have its own components, hook, style...
-  Anything shareable throughout the react app will stay in the root of the "ui" folder, such as the "component" or "style" folder. The component folder in ui must only have atomic component (shareable)

### CODE REVIEW

**Review by 0xLodz — COMMENTED** [review]
The `view` folder is a bit confusing to me. That's not simple to find a more appropriate name though.

What do you think about having a folder structure like this ?

```
ui
  |- component
  |   |
  |   |- shared
  |   |   |- button
  |   |
  |   |- dataverse
  |   |   |- dataverseItemCard
 ```

**Comment by ccamel** [comment]
@GeoffreyPicard this is minor but your commit description should start by a verb (see [wiki](https://github.com/okp4/wiki/wiki/Naming-rules#commit-messages)):

Something like that (you can adapt):
```diff
- refactor: architectural change for react app
+ refactor: revamp UI folder structure and file organization
```

**Review by fredericvilcot — APPROVED** [review]

**Review by lolottetheclash — APPROVED** [review]

**Review by ccamel — APPROVED** [review]
LGTM!

**Comment by fredericvilcot** [comment]
Please @GeoffreyPicard add a GPG key to sign your commits

**Pull request merged**
