### PR TITLE
feat(layout): fix sidebar & toolbar position in viewport

### PR DESCRIPTION
**Pull request by ErikssonJoakim**
This PR makes the sidebar and toolbar have a fixed position.
- #117

By request I've also done the following:
- added a bottom padding 
- modified the sidebar nav block gaps 
- customized the scrollbar (transparency & size)

<details>
<summary>1440px</summary>

127 0 0 1_5173_dataverse (5)
127 0 0 1_5173_dataverse

</details>

<details>
<summary>768px</summary>

127 0 0 1_5173_dataverse (4)
127 0 0 1_5173_dataverse (1)

</details>

<details>
<summary>375px</summary>

127 0 0 1_5173_dataverse (3)
127 0 0 1_5173_dataverse (2)

</details>

### CODE REVIEW

**Review by lolottetheclash — CHANGES_REQUESTED** [review]
I think the `last-child` css selector is not robust: what will happen if there is not only the toolbar and the main page, but also other elements? the last child will not necessarily select the right element... don't you think @fredericvilcot ?

**Comment by fredericvilcot** [comment]
> I think the `last-child` css selector is not robust: what will happen if there is not only the toolbar and the main page, but also other elements? the last child will not necessarily select the right element... don't you think @fredericvilcot ?

Yes, would be better to target the `className` IMHO

**Comment by ErikssonJoakim** [comment]
Yes you are correct. I've added a wrapper class name to avoid potential issues. I've also reworked the layout padding to be able to position the scrollbar more to the right, please see updated images

**Review by ccamel — APPROVED** [review]
:+1:

**Review by ccamel — APPROVED** [review]

**Pull request merged**
