### PR TITLE
ci(workflow): add lighthouse lint

### PR DESCRIPTION
**Pull request by ccamel**
Introduces a new job to check performance of the webapp by using [lighthouse-check-action](https://github.com/foo-software/lighthouse-check-action) by publishing the indicators on PR reviews. 

It's important to note that at present, no checks have been put in place to ensure that the metrics meet certain minimum standards.

### CODE REVIEW

**Review by amimart — APPROVED** [review]
Nice one 💪

**Comment by ccamel** [comment]
@fredericvilcot is it ok for you?

**Comment by fredericvilcot** [comment]
@ccamel 
Great job, thanks.

I still wonder what methods of calculation these results are based on, because I don't get the same notation when I run the lighthouse extension in Chrome on the staging url:

Capture d’écran 2023-02-28 à 15 10 26

**Comment by ccamel** [comment]
@fredericvilcot I don't know how the results are based on. It is possible that there are multiple factors that could affect the outcome, including network conditions and device capabilities. I think it would be interresting to monitor the progress of the metrics over PRs and check that they are stable and consistent.

**Comment by ccamel** [comment]
Btw That being said, I would like to emphasize the importance of having such tools to improve the quality of our web deliverables, provided of course that we can aknowledge the results.

**Pull request merged**
