### PR TITLE
refactor: update all responsive functions to use use-breakpoints() func

### PR DESCRIPTION
**Pull request by AnjaMis**
This PR updates all responsive functions to use use-function() functions in all files.

### CODE REVIEW

**Comment by fredericvilcot** [comment]
@AnjaMis 
Is this PR ready to review?

**Comment by AnjaMis** [comment]
@fredericvilcot yess it is!

**Comment by fredericvilcot** [comment]
@AnjaMis 
There are no reviewers 😅

**Review by ErikssonJoakim — APPROVED** [review]
Looks good 😃 👍 I just got a minor suggestion

**Review by ErikssonJoakim — APPROVED** [review]

**Review by ccamel — APPROVED** [review]
LGTM! Thanks.

**Review by lolottetheclash — APPROVED** [review]
Nice 👍

**Pull request merged**
